services:
  - type: web
    name: kem-y-suong-api
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: APP_BASE_URL
        value: https://kem-y-suong-api.onrender.com
      - key: FRONTEND_URL
        value: https://kem-y-suong.vercel.app
      - key: CORS_ORIGIN
        value: https://kem-y-suong.vercel.app,https://ice-cream-123.vercel.app
      - key: MONGO_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: ACCESS_TOKEN_EXPIRES
        value: 15m
      - key: REFRESH_TOKEN_EXPIRES
        value: 7d
